export const FEATURE_NAMES = [
  'conceptPreview',
  'publicWebsite',
  'onlineBooking',
  'guestAccounts',
  'guestBookingHistory',
  'whatsappContact',
  'staffDashboard',
  'bookingManagement',
  'availabilityManagement',
  'contentManagement',
  'payments',
  'mobileMoney',
  'multiBusiness',
  'businessOnboarding',
  'businessSwitching',
  'restaurantModule',
  'recreationModule',
  'eventVenueModule',
  'reviews',
  'advancedAnalytics',
  'customDomains',
  'staffInvitations',
] as const;

export type FeatureName = (typeof FEATURE_NAMES)[number];

export const PUBLIC_FEATURE_NAMES = [
  'conceptPreview',
  'publicWebsite',
  'onlineBooking',
  'guestAccounts',
  'guestBookingHistory',
  'whatsappContact',
] as const satisfies readonly FeatureName[];

export type PublicFeatureName = (typeof PUBLIC_FEATURE_NAMES)[number];

export const FEATURE_ENV_KEYS: Record<FeatureName, string> = {
  conceptPreview: 'FEATURE_CONCEPT_PREVIEW',
  publicWebsite: 'FEATURE_PUBLIC_WEBSITE',
  onlineBooking: 'FEATURE_ONLINE_BOOKING',
  guestAccounts: 'FEATURE_GUEST_ACCOUNTS',
  guestBookingHistory: 'FEATURE_GUEST_BOOKING_HISTORY',
  whatsappContact: 'FEATURE_WHATSAPP_CONTACT',
  staffDashboard: 'FEATURE_STAFF_DASHBOARD',
  bookingManagement: 'FEATURE_BOOKING_MANAGEMENT',
  availabilityManagement: 'FEATURE_AVAILABILITY_MANAGEMENT',
  contentManagement: 'FEATURE_CONTENT_MANAGEMENT',
  payments: 'FEATURE_PAYMENTS',
  mobileMoney: 'FEATURE_MOBILE_MONEY',
  multiBusiness: 'FEATURE_MULTI_BUSINESS',
  businessOnboarding: 'FEATURE_BUSINESS_ONBOARDING',
  businessSwitching: 'FEATURE_BUSINESS_SWITCHING',
  restaurantModule: 'FEATURE_RESTAURANT_MODULE',
  recreationModule: 'FEATURE_RECREATION_MODULE',
  eventVenueModule: 'FEATURE_EVENT_VENUE_MODULE',
  reviews: 'FEATURE_REVIEWS',
  advancedAnalytics: 'FEATURE_ADVANCED_ANALYTICS',
  customDomains: 'FEATURE_CUSTOM_DOMAINS',
  staffInvitations: 'FEATURE_STAFF_INVITATIONS',
};

export const FEATURE_DEFAULTS: Readonly<Record<FeatureName, boolean>> = {
  conceptPreview: true,
  publicWebsite: true,
  onlineBooking: true,
  guestAccounts: true,
  guestBookingHistory: true,
  whatsappContact: true,
  staffDashboard: true,
  bookingManagement: true,
  availabilityManagement: true,
  contentManagement: true,
  payments: false,
  mobileMoney: false,
  multiBusiness: false,
  businessOnboarding: false,
  businessSwitching: false,
  restaurantModule: false,
  recreationModule: false,
  eventVenueModule: false,
  reviews: false,
  advancedAnalytics: false,
  customDomains: false,
  staffInvitations: false,
};
