export const RED_MASAI_DEMO_MEDIA_ENABLED =
  process.env.NEXT_PUBLIC_RED_MASAI_DEMO_MEDIA === "true";

export function parseRedMasaiDemoMediaFlag(value: string | undefined) {
  return value === "true";
}

export type RedMasaiMediaType = "image" | "video";
export type RedMasaiMediaCategory =
  | "stay"
  | "experience"
  | "celebrate"
  | "create";
export type RedMasaiMediaApproval =
  | "private-demo"
  | "owner-approval-required";

export type RedMasaiMediaRecord = {
  key: string;
  src: string;
  type: RedMasaiMediaType;
  category: RedMasaiMediaCategory;
  alt: string;
  width: number;
  height: number;
  aspectRatio: `${number} / ${number}`;
  objectPosition: string;
  approval: RedMasaiMediaApproval;
  recognizablePeople: boolean;
  screenOrPosterWarning: boolean;
  commercialInclusionWarning: boolean;
  fallbackLabel: string;
  intendedPages: readonly string[];
  intendedSections: readonly string[];
};

const image = (
  record: Omit<RedMasaiMediaRecord, "type" | "aspectRatio">,
): RedMasaiMediaRecord => ({
  ...record,
  type: "image",
  aspectRatio: `${record.width} / ${record.height}`,
});

const base = "/media/red-masai/concept";

export const redMasaiMedia = {
  homeHeroStay: image({
    key: "homeHeroStay",
    src: `${base}/stay/bedroom-orange-wide.jpeg`,
    category: "stay",
    alt: "Warm orange bedroom with a double bed, desk and pendant light.",
    width: 1125,
    height: 1503,
    objectPosition: "50% 43%",
    approval: "private-demo",
    recognizablePeople: false,
    screenOrPosterWarning: false,
    commercialInclusionWarning: true,
    fallbackLabel: "A warm private stay",
    intendedPages: ["/", "/apartments"],
    intendedSections: ["homepage hero", "stay introduction"],
  }),
  homeHeroGarden: image({
    key: "homeHeroGarden",
    src: `${base}/experience/garden-picnic-wide.jpeg`,
    category: "experience",
    alt: "Garden picnic setting beneath palms and warm string lights.",
    width: 1125,
    height: 1122,
    objectPosition: "50% 48%",
    approval: "owner-approval-required",
    recognizablePeople: true,
    screenOrPosterWarning: false,
    commercialInclusionWarning: true,
    fallbackLabel: "Garden moments",
    intendedPages: ["/", "/experiences", "/celebrate"],
    intendedSections: ["homepage hero", "garden lead", "celebrate setting"],
  }),
  homeHeroCinema: image({
    key: "homeHeroCinema",
    src: `${base}/experience/cinema-01.jpeg`,
    category: "experience",
    alt: "Private cinema room with lounge seating and a wall projection.",
    width: 1125,
    height: 1015,
    objectPosition: "64% 50%",
    approval: "owner-approval-required",
    recognizablePeople: true,
    screenOrPosterWarning: true,
    commercialInclusionWarning: false,
    fallbackLabel: "Private cinema atmosphere",
    intendedPages: ["/", "/experiences"],
    intendedSections: ["homepage hero", "cinema lead"],
  }),
  homeHeroExterior: image({
    key: "homeHeroExterior",
    src: `${base}/stay/exterior-night.jpeg`,
    category: "stay",
    alt: "Red Masai exterior and garden foliage illuminated at night.",
    width: 1125,
    height: 1503,
    objectPosition: "52% 38%",
    approval: "owner-approval-required",
    recognizablePeople: false,
    screenOrPosterWarning: false,
    commercialInclusionWarning: false,
    fallbackLabel: "Red Masai after dark",
    intendedPages: ["/", "/location", "/gallery"],
    intendedSections: ["hero accent", "location", "property gallery"],
  }),
  stayBedroomPrimary: image({
    key: "stayBedroomPrimary",
    src: `${base}/stay/bedroom-orange-close.jpeg`,
    category: "stay",
    alt: "Orange bedding in a softly lit bedroom with two windows.",
    width: 1125,
    height: 1479,
    objectPosition: "50% 52%",
    approval: "private-demo",
    recognizablePeople: false,
    screenOrPosterWarning: false,
    commercialInclusionWarning: false,
    fallbackLabel: "Bedroom visual reference",
    intendedPages: ["/apartments", "/apartments/[id]", "/gallery"],
    intendedSections: ["stay cards", "stay gallery"],
  }),
  stayBedroomSecondary: image({
    key: "stayBedroomSecondary",
    src: `${base}/stay/bedroom-white-night.jpeg`,
    category: "stay",
    alt: "White bedroom prepared for the evening with soft ambient lighting.",
    width: 1125,
    height: 1131,
    objectPosition: "50% 53%",
    approval: "private-demo",
    recognizablePeople: false,
    screenOrPosterWarning: true,
    commercialInclusionWarning: false,
    fallbackLabel: "Evening bedroom atmosphere",
    intendedPages: ["/apartments/[id]", "/gallery"],
    intendedSections: ["stay gallery"],
  }),
  stayLivingRoom: image({
    key: "stayLivingRoom",
    src: `${base}/stay/living-room-flower.jpeg`,
    category: "stay",
    alt: "Orange flowers frame a relaxed living area with low seating.",
    width: 1125,
    height: 1485,
    objectPosition: "62% 52%",
    approval: "private-demo",
    recognizablePeople: false,
    screenOrPosterWarning: true,
    commercialInclusionWarning: false,
    fallbackLabel: "Living space visual reference",
    intendedPages: ["/apartments/[id]", "/about", "/gallery"],
    intendedSections: ["stay gallery", "our story"],
  }),
  stayEntertainment: image({
    key: "stayEntertainment",
    src: `${base}/stay/lounge-tv.jpeg`,
    category: "stay",
    alt: "Orange-accented lounge with seating, a table and indoor plants.",
    width: 1125,
    height: 1488,
    objectPosition: "55% 69%",
    approval: "owner-approval-required",
    recognizablePeople: false,
    screenOrPosterWarning: true,
    commercialInclusionWarning: true,
    fallbackLabel: "Lounge and leisure",
    intendedPages: ["/apartments/[id]", "/experiences", "/gallery"],
    intendedSections: ["stay gallery", "games and leisure"],
  }),
  stayBalcony: image({
    key: "stayBalcony",
    src: `${base}/stay/balcony-reading.jpeg`,
    category: "stay",
    alt: "A guest reads on a balcony overlooking the garden.",
    width: 1125,
    height: 1504,
    objectPosition: "50% 60%",
    approval: "private-demo",
    recognizablePeople: false,
    screenOrPosterWarning: false,
    commercialInclusionWarning: false,
    fallbackLabel: "A quiet balcony moment",
    intendedPages: ["/apartments/[id]", "/about", "/gallery"],
    intendedSections: ["stay gallery", "our story"],
  }),
  stayBathroomBath: image({
    key: "stayBathroomBath",
    src: `${base}/stay/bathroom-bathtub.jpeg`,
    category: "stay",
    alt: "Bathtub and shower fittings in a tiled bathroom.",
    width: 1125,
    height: 1147,
    objectPosition: "42% 56%",
    approval: "private-demo",
    recognizablePeople: false,
    screenOrPosterWarning: false,
    commercialInclusionWarning: true,
    fallbackLabel: "Bathroom visual reference",
    intendedPages: ["/apartments/[id]", "/gallery"],
    intendedSections: ["detailed stay gallery"],
  }),
  stayBathroomShower: image({
    key: "stayBathroomShower",
    src: `${base}/stay/bathroom-shower.jpeg`,
    category: "stay",
    alt: "Walk-in shower with a rainfall shower head and patterned tiles.",
    width: 1125,
    height: 1506,
    objectPosition: "62% 45%",
    approval: "private-demo",
    recognizablePeople: false,
    screenOrPosterWarning: false,
    commercialInclusionWarning: true,
    fallbackLabel: "Shower visual reference",
    intendedPages: ["/apartments/[id]", "/gallery"],
    intendedSections: ["detailed stay gallery"],
  }),
  stayBathroomToilet: image({
    key: "stayBathroomToilet",
    src: `${base}/stay/bathroom-toilet.jpeg`,
    category: "stay",
    alt: "Toilet and hand spray in the tiled bathroom.",
    width: 1125,
    height: 1487,
    objectPosition: "50% 48%",
    approval: "private-demo",
    recognizablePeople: false,
    screenOrPosterWarning: false,
    commercialInclusionWarning: true,
    fallbackLabel: "Bathroom detail",
    intendedPages: ["/apartments/[id]", "/gallery"],
    intendedSections: ["detailed stay gallery last"],
  }),
  stayExterior: image({
    key: "stayExterior",
    src: `${base}/stay/exterior-night.jpeg`,
    category: "stay",
    alt: "Red Masai exterior and garden foliage illuminated at night.",
    width: 1125,
    height: 1503,
    objectPosition: "52% 38%",
    approval: "owner-approval-required",
    recognizablePeople: false,
    screenOrPosterWarning: false,
    commercialInclusionWarning: false,
    fallbackLabel: "Property exterior",
    intendedPages: ["/apartments/[id]", "/location", "/gallery"],
    intendedSections: ["stay gallery", "location"],
  }),
  experienceCinema: image({
    key: "experienceCinema",
    src: `${base}/experience/cinema-01.jpeg`,
    category: "experience",
    alt: "Private cinema room with lounge seating and a wall projection.",
    width: 1125,
    height: 1015,
    objectPosition: "65% 50%",
    approval: "owner-approval-required",
    recognizablePeople: true,
    screenOrPosterWarning: true,
    commercialInclusionWarning: false,
    fallbackLabel: "Private cinema atmosphere",
    intendedPages: ["/experiences", "/gallery"],
    intendedSections: ["cinema lead"],
  }),
  experienceGardenWide: image({
    key: "experienceGardenWide",
    src: `${base}/experience/garden-picnic-wide.jpeg`,
    category: "experience",
    alt: "Garden picnic setting beneath palms and warm string lights.",
    width: 1125,
    height: 1122,
    objectPosition: "50% 48%",
    approval: "owner-approval-required",
    recognizablePeople: true,
    screenOrPosterWarning: false,
    commercialInclusionWarning: true,
    fallbackLabel: "Garden setting",
    intendedPages: ["/experiences", "/celebrate", "/gallery"],
    intendedSections: ["garden lead", "celebrate lead"],
  }),
  experienceGardenDetail: image({
    key: "experienceGardenDetail",
    src: `${base}/experience/garden-picnic-detail.jpeg`,
    category: "experience",
    alt: "Picnic blankets, cushions, fruit and lights arranged in the garden.",
    width: 1125,
    height: 1131,
    objectPosition: "50% 45%",
    approval: "owner-approval-required",
    recognizablePeople: true,
    screenOrPosterWarning: false,
    commercialInclusionWarning: true,
    fallbackLabel: "Garden gathering detail",
    intendedPages: ["/experiences", "/celebrate", "/gallery"],
    intendedSections: ["garden detail", "celebrate detail"],
  }),
  experienceRomanticBath: image({
    key: "experienceRomanticBath",
    src: `${base}/experience/romantic-bath.jpeg`,
    category: "experience",
    alt: "Candlelit bath arranged as a private relaxation concept.",
    width: 1125,
    height: 1134,
    objectPosition: "58% 67%",
    approval: "owner-approval-required",
    recognizablePeople: false,
    screenOrPosterWarning: true,
    commercialInclusionWarning: true,
    fallbackLabel: "Private relaxation concept",
    intendedPages: ["/experiences", "/gallery"],
    intendedSections: ["romantic relaxation"],
  }),
  experienceGamesCheckers: image({
    key: "experienceGamesCheckers",
    src: `${base}/experience/checkers.jpeg`,
    category: "experience",
    alt: "A guest moves a piece on a wooden checkers board beside a lantern.",
    width: 1125,
    height: 1503,
    objectPosition: "52% 37%",
    approval: "private-demo",
    recognizablePeople: false,
    screenOrPosterWarning: false,
    commercialInclusionWarning: true,
    fallbackLabel: "Games and shared time",
    intendedPages: ["/experiences", "/about", "/gallery"],
    intendedSections: ["games and leisure", "our story"],
  }),
  experienceGamesPool: image({
    key: "experienceGamesPool",
    src: `${base}/experience/pool-table.jpeg`,
    category: "experience",
    alt: "Pool table in a covered leisure area with stone walls.",
    width: 1125,
    height: 1498,
    objectPosition: "50% 52%",
    approval: "owner-approval-required",
    recognizablePeople: false,
    screenOrPosterWarning: false,
    commercialInclusionWarning: true,
    fallbackLabel: "Leisure area",
    intendedPages: ["/experiences", "/gallery"],
    intendedSections: ["games and leisure"],
  }),
  celebrateGardenDinner: image({
    key: "celebrateGardenDinner",
    src: `${base}/celebrate/garden-dinner.jpeg`,
    category: "celebrate",
    alt: "Guests share an evening meal at a warmly lit garden table.",
    width: 1125,
    height: 1266,
    objectPosition: "52% 42%",
    approval: "owner-approval-required",
    recognizablePeople: true,
    screenOrPosterWarning: false,
    commercialInclusionWarning: true,
    fallbackLabel: "An intimate garden celebration",
    intendedPages: ["/celebrate", "/gallery"],
    intendedSections: ["garden dinner", "gather gallery"],
  }),
  celebratePicnicGroup: image({
    key: "celebratePicnicGroup",
    src: `${base}/celebrate/garden-picnic-group.jpeg`,
    category: "celebrate",
    alt: "Three guests relax together on a garden picnic arrangement.",
    width: 1125,
    height: 1103,
    objectPosition: "50% 55%",
    approval: "owner-approval-required",
    recognizablePeople: true,
    screenOrPosterWarning: false,
    commercialInclusionWarning: true,
    fallbackLabel: "A private group moment",
    intendedPages: ["/celebrate", "/gallery"],
    intendedSections: ["private gathering", "gather gallery"],
  }),
  createEventPreparationVideo: {
    key: "createEventPreparationVideo",
    src: `${base}/create/event-preparation.mp4`,
    type: "video",
    category: "create",
    alt: "Video showing food preparation, event setup and a venue transformation for lifestyle content.",
    width: 512,
    height: 910,
    aspectRatio: "512 / 910",
    objectPosition: "50% 50%",
    approval: "owner-approval-required",
    recognizablePeople: true,
    screenOrPosterWarning: true,
    commercialInclusionWarning: true,
    fallbackLabel: "Event preparation and venue transformation",
    intendedPages: ["/create", "/gallery"],
    intendedSections: ["create lead", "create gallery"],
  },
  createEventPreparationPoster: image({
    key: "createEventPreparationPoster",
    src: `${base}/create/event-preparation-poster.jpg`,
    category: "create",
    alt: "Presenter introducing an event preparation and venue transformation video.",
    width: 512,
    height: 910,
    objectPosition: "50% 42%",
    approval: "owner-approval-required",
    recognizablePeople: true,
    screenOrPosterWarning: false,
    commercialInclusionWarning: false,
    fallbackLabel: "Create at Red Masai",
    intendedPages: ["/create", "/gallery"],
    intendedSections: ["video poster", "create gallery"],
  }),
} as const satisfies Record<string, RedMasaiMediaRecord>;

export type RedMasaiMediaKey = keyof typeof redMasaiMedia;

export const redMasaiMediaKeys = Object.keys(
  redMasaiMedia,
) as RedMasaiMediaKey[];

export function getRedMasaiMedia(key: RedMasaiMediaKey) {
  return redMasaiMedia[key];
}

export function hasUniqueRedMasaiMediaKeys() {
  return new Set(redMasaiMediaKeys).size === redMasaiMediaKeys.length;
}

export const promotionalMediaKeys: readonly RedMasaiMediaKey[] = [
  "homeHeroStay",
  "homeHeroGarden",
  "homeHeroCinema",
  "homeHeroExterior",
  "stayBedroomPrimary",
];
